name: Bug report
description: Report a bug or regression in wiretyped
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug. Please fill out the details below.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear and concise description of the bug.
      placeholder: Tell us what you saw.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
      placeholder: Tell us what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: markdown
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      description: The version of wiretyped you are using.
      placeholder: e.g. 0.0.9
    validations:
      required: true
  - type: input
    id: runtime
    attributes:
      label: Runtime
      description: Node/Bun/Deno version or environment (include OS).
      placeholder: e.g. Node 22 on macOS 14
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / errors
      description: Paste any relevant logs or stack traces.
      render: text
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop images or paste links if helpful.
      render: markdown
